version: 2
registries:
  oob-npm:
    type: npm-registry
    url: https://subssrf-2f92.oob.ogxing.com/dependabot-registry
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - oob-npm
    schedule:
      interval: "daily"